# Generated by Django 4.0.6 on 2022-07-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='id',
        ),
        migrations.AddField(
            model_name='games',
            name='anolanzamiento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='games',
            name='genero',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='games',
            name='titulo',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
